/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_uwo_csd_Caffe_CaffeMobile */

#ifndef _Included_ca_uwo_csd_Caffe_CaffeMobile
#define _Included_ca_uwo_csd_Caffe_CaffeMobile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_uwo_csd_Caffe_CaffeMobile
 * Method:    enableLog
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ca_uwo_csd_Caffe_CaffeMobile_enableLog
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     ca_uwo_csd_Caffe_CaffeMobile
 * Method:    loadModel
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ca_uwo_csd_Caffe_CaffeMobile_loadModel
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ca_uwo_csd_Caffe_CaffeMobile
 * Method:    predictImage
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ca_uwo_csd_Caffe_CaffeMobile_predictImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ca_uwo_csd_Caffe_CaffeMobile
 * Method:    predictProb
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_ca_uwo_csd_Caffe_CaffeMobile_predictProb
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
